$urls = "http://cdn.caredfor.com/assets/emails/sober-birthday-email-background.png"`
,"http://cdn.caredfor.com/assets/emails/app-icons-background.png"`
,"http://cdn.caredfor.com/assets/emails/app-icons-background~red.png"`
,"http://cdn.caredfor.com/assets/emails/app-store.png"`
,"http://cdn.caredfor.com/assets/emails/google-play.png"`
,"http://cdn.caredfor.com/assets/bg1.jpg"`
,"http://cdn.caredfor.com/assets/bg2.jpg"`
,"http://cdn.caredfor.com/assets/bg3.jpg"`
,"http://cdn.caredfor.com/assets/bg5.jpg"`
,"http://cdn.caredfor.com/assets/bg6.jpg"`
,"http://cdn.caredfor.com/assets/bg7.jpg"`
,"http://cdn.caredfor.com/assets/bg8.jpg"`
,"http://cdn.caredfor.com/assets/bg9.jpg"`
,"http://cdn.caredfor.com/assets/bg10.jpg"`
,"http://cdn.caredfor.com/assets/bg11.jpg"`
,"http://cdn.caredfor.com/assets/bg12.jpg"`
,"http://cdn.caredfor.com/assets/bg13.jpg"`
,"http://cdn.caredfor.com/assets/bg14.jpg"`
,"http://cdn.caredfor.com/assets/bg15.jpg"`
,"http://cdn.caredfor.com/assets/bg16.jpg"`
,"http://cdn.caredfor.com/assets/bg18.jpg"`
,"http://cdn.caredfor.com/assets/bg19.jpg"`
,"http://cdn.caredfor.com/assets/bg20.jpg"`
,"http://cdn.caredfor.com/assets/bg21.jpg"`
,"http://cdn.caredfor.com/assets/bg22.jpg"`
,"http://cdn.caredfor.com/assets/bg23.jpg"`
,"http://cdn.caredfor.com/assets/bg24.jpg"`
,"http://cdn.caredfor.com/assets/bg25.jpg"`
,"http://cdn.caredfor.com/assets/bg27.jpg"`
,"http://cdn.caredfor.com/assets/bg28.jpg"`
,"http://cdn.caredfor.com/assets/bg29.jpg"`
,"http://cdn.caredfor.com/assets/bg30.jpg"`
,"http://cdn.caredfor.com/assets/bg31.jpg"`
,"http://cdn.caredfor.com/assets/bg32.jpg"`
,"http://cdn.caredfor.com/assets/bg33.jpg"`
,"http://cdn.caredfor.com/assets/bg34.jpg"`
,"http://cdn.caredfor.com/assets/bg35.jpg"`
,"http://cdn.caredfor.com/assets/bg36.jpg"`
,"http://cdn.caredfor.com/assets/bg37.jpg"`
,"http://cdn.caredfor.com/assets/bg38.jpg"`
,"http://cdn.caredfor.com/assets/bg39.jpg"`
,"http://cdn.caredfor.com/assets/bg41.jpg"`
,"http://cdn.caredfor.com/assets/bg42.jpg"`
,"http://cdn.caredfor.com/assets/bg43.jpg"`
,"http://cdn.caredfor.com/assets/bg44.jpg"`
,"http://cdn.caredfor.com/assets/bg45.jpg"`
,"http://cdn.caredfor.com/assets/bg46.jpg"`
,"http://cdn.caredfor.com/assets/bg47.jpg"`
,"http://cdn.caredfor.com/assets/bg48.jpg"`
,"http://cdn.caredfor.com/assets/bg49.jpg"`
,"http://cdn.caredfor.com/assets/bg50.jpg"`
,"http://cdn.caredfor.com/assets/bg51.jpg"`
,"http://cdn.caredfor.com/assets/bg52.jpg"`
,"http://cdn.caredfor.com/assets/bg53.jpg"`
,"http://cdn.caredfor.com/assets/bg54.jpg"`
,"http://cdn.caredfor.com/assets/bg55.jpg"`
,"http://cdn.caredfor.com/assets/bg56.jpg"`
,"http://cdn.caredfor.com/assets/bg57.jpg"`
,"http://cdn.caredfor.com/assets/bg58.jpg"`
,"http://cdn.caredfor.com/assets/bg59.jpg"`
,"http://cdn.caredfor.com/assets/bg60.jpg"`
,"http://cdn.caredfor.com/assets/bg61.jpg"`
,"http://cdn.caredfor.com/assets/bg62.jpg"`
,"http://cdn.caredfor.com/assets/bg63.jpg"`
,"http://cdn.caredfor.com/assets/bg64.jpg"`
,"http://cdn.caredfor.com/assets/bg65.jpg"`
,"http://cdn.caredfor.com/assets/bg66.jpg"`
,"http://cdn.caredfor.com/assets/bg67.jpg"`
,"http://cdn.caredfor.com/assets/bg68.jpg"`
,"http://cdn.caredfor.com/assets/bg69.jpg"`
,"http://cdn.caredfor.com/assets/bg70.jpg"`
,"http://cdn.caredfor.com/assets/bg71.jpg"`
,"http://cdn.caredfor.com/assets/bg72.jpg"`
,"http://cdn.caredfor.com/assets/bg73.jpg"`
,"http://cdn.caredfor.com/assets/bg74.jpg"`
,"http://cdn.caredfor.com/assets/bg75.jpg"`
,"http://cdn.caredfor.com/assets/bg76.jpg"`
,"http://cdn.caredfor.com/assets/bg77.jpg"`
,"http://cdn.caredfor.com/assets/bg78.jpg"`
,"http://cdn.caredfor.com/assets/bg79.jpg"`
,"http://cdn.caredfor.com/assets/bg80.jpg"`
,"http://cdn.caredfor.com/assets/bg81.jpg"`
,"http://cdn.caredfor.com/assets/bg82.jpg"`
,"http://cdn.caredfor.com/assets/bg83.jpg"`
,"http://cdn.caredfor.com/assets/bg84.jpg"`
,"http://cdn.caredfor.com/assets/bg85.jpg"`
,"http://cdn.caredfor.com/assets/bg86.jpg"`
,"http://cdn.caredfor.com/assets/bg87.jpg"`
,"http://cdn.caredfor.com/assets/bg88.jpg"`
,"http://cdn.caredfor.com/assets/bg89.jpg"`
,"http://cdn.caredfor.com/assets/bg90.jpg"`
,"http://cdn.caredfor.com/assets/bg91.jpg"`
,"http://cdn.caredfor.com/assets/bg92.jpg"`
,"http://cdn.caredfor.com/assets/bg93.jpg"`
,"http://cdn.caredfor.com/assets/bg94.jpg"`
,"http://cdn.caredfor.com/assets/bg95.jpg"`
,"http://cdn.caredfor.com/assets/bg96.jpg"`
,"http://cdn.caredfor.com/assets/bg97.jpg"`
,"http://cdn.caredfor.com/assets/bg98.jpg"`
,"http://cdn.caredfor.com/assets/bg99.jpg"`
,"http://cdn.caredfor.com/assets/bg100.jpg"`
,"http://cdn.caredfor.com/assets/bg101.jpg"`
,"http://cdn.caredfor.com/assets/bg102.jpg"`
,"http://cdn.caredfor.com/assets/bg103.jpg"`
,"http://cdn.caredfor.com/assets/bg104.jpg"`
,"http://cdn.caredfor.com/assets/bg105.jpg"`
,"http://cdn.caredfor.com/assets/bg106.jpg"`
,"http://cdn.caredfor.com/assets/bg107.jpg"`
,"http://cdn.caredfor.com/assets/bg108.jpg"`
,"http://cdn.caredfor.com/assets/bg109.jpg"`
,"http://cdn.caredfor.com/assets/bg110.jpg"`
,"http://cdn.caredfor.com/assets/bg111.jpg"`
,"http://cdn.caredfor.com/assets/bg112.jpg"`
,"http://cdn.caredfor.com/assets/bg113.jpg"`

Set-Location C:\temp 
foreach ($url in $urls) {
    Invoke-WebRequest -Uri $url -OutFile $(split-path -Leaf "$url")
}

# //,"http://cdn.caredfor.com/assets/bg4.jpg"`
# //,"http://cdn.caredfor.com/assets/bg17.jpg"`
# //,"http://cdn.caredfor.com/assets/bg26.jpg"`
# //,"http://cdn.caredfor.com/assets/bg40.jpg"`